### ISSUE TITLE
Use minecraft argument types

### ISSUE THREAD

**Issue by Hamme05** [CottonMC/ClientCommands#10]
How do i I use for example "EntityArgumentType" as argument?

**Comment by Juuxel** [comment]
You can use them in the same way as with normal commands. There are four different entity argument types:
- `EntityArgumentType.entity()`: one entity
- `EntityArgumentType.entities()`: many entities
- `EntityArgumentType.player()`: one player
- `EntityArgumentType.players()`: many players

Then you can do the normal `ArgumentBuilders.argument(<your argument name>, EntityArgumentType.entity() /* or one of those others */)`.
