### ISSUE TITLE
Backport

### ISSUE THREAD

**Issue by creeper123123321** [CottonMC/ClientCommands#13]
**Is your feature request related to a problem? Please describe.**
I need 1.8.9 CCC for backporting ViaFabric

**Describe the solution you'd like**
A backport of CCC

**Describe alternatives you've considered**
Not using CCC

**Additional context**
ViaVersion/ViaFabric#16

**Comment by Juuxel** [comment]
I'm not supporting outdated releases -- especially ones that are almost five years old.
