### ISSUE TITLE
http://server.bbkr.space:8081 is down

### ISSUE THREAD

**Issue by matthew-cline** [CottonMC/ClientCommands#8]
Clicking on  [http://server.bbkr.space:8081/artifactory/libs-snapshot](http://server.bbkr.space:8081/artifactory/libs-snapshot)  gets a popup for HTTP authentication, and clicking on [http://server.bbkr.space:8081/](http://server.bbkr.space:8081/) redirects to a JFrog login pagin,

**Comment by Boundarybreaker** [comment]
As per the announcement in the Cotton discord, there are issues with the Maven currently. I’m working on fixing them as we speak. Please be patient.

**Comment by Boundarybreaker** [comment]
This is now fixed.
